/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as fakeDexEscrowSol from "./FakeDexEscrow.sol";
export type { fakeDexEscrowSol };
export type { TFAKEUSD } from "./TFAKEUSD";
