/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface FakeDexEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "backendSigner"
      | "canClaim"
      | "claimToTrading"
      | "dailyWithdrawalLimit"
      | "dailyWithdrawn"
      | "deposit"
      | "emergencyWithdraw"
      | "escrowBalance"
      | "faucetAmount"
      | "faucetCooldown"
      | "lastFaucetClaim"
      | "lastWithdrawalDay"
      | "maxWithdrawalPerTx"
      | "owner"
      | "remainingDailyWithdrawal"
      | "renounceOwnership"
      | "setBackendSigner"
      | "setFaucetSettings"
      | "setWithdrawalLimits"
      | "timeUntilNextClaim"
      | "token"
      | "totalDeposited"
      | "totalFaucetClaims"
      | "totalWithdrawn"
      | "transferOwnership"
      | "withdraw"
      | "withdrawalNonces"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BackendSignerUpdated"
      | "DepositedToTrading"
      | "FaucetClaimedToTrading"
      | "FaucetSettingsUpdated"
      | "OwnershipTransferred"
      | "WithdrawalLimitsUpdated"
      | "WithdrawnFromTrading"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "backendSigner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "canClaim",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimToTrading",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dailyWithdrawalLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dailyWithdrawn",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "escrowBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "faucetAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "faucetCooldown",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastFaucetClaim",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastWithdrawalDay",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxWithdrawalPerTx",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "remainingDailyWithdrawal",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBackendSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFaucetSettings",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setWithdrawalLimits",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "timeUntilNextClaim",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalDeposited",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalFaucetClaims",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalWithdrawn",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalNonces",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "backendSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canClaim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimToTrading",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyWithdrawalLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyWithdrawn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "escrowBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "faucetAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "faucetCooldown",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastFaucetClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastWithdrawalDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxWithdrawalPerTx",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "remainingDailyWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBackendSigner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFaucetSettings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWithdrawalLimits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "timeUntilNextClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalDeposited",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalFaucetClaims",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalWithdrawn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalNonces",
    data: BytesLike
  ): Result;
}

export namespace BackendSignerUpdatedEvent {
  export type InputTuple = [oldSigner: AddressLike, newSigner: AddressLike];
  export type OutputTuple = [oldSigner: string, newSigner: string];
  export interface OutputObject {
    oldSigner: string;
    newSigner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedToTradingEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FaucetClaimedToTradingEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FaucetSettingsUpdatedEvent {
  export type InputTuple = [amount: BigNumberish, cooldown: BigNumberish];
  export type OutputTuple = [amount: bigint, cooldown: bigint];
  export interface OutputObject {
    amount: bigint;
    cooldown: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalLimitsUpdatedEvent {
  export type InputTuple = [maxPerTx: BigNumberish, dailyLimit: BigNumberish];
  export type OutputTuple = [maxPerTx: bigint, dailyLimit: bigint];
  export interface OutputObject {
    maxPerTx: bigint;
    dailyLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnFromTradingEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FakeDexEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): FakeDexEscrow;
  waitForDeployment(): Promise<this>;

  interface: FakeDexEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  backendSigner: TypedContractMethod<[], [string], "view">;

  canClaim: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  claimToTrading: TypedContractMethod<[], [void], "nonpayable">;

  dailyWithdrawalLimit: TypedContractMethod<[], [bigint], "view">;

  dailyWithdrawn: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  deposit: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  emergencyWithdraw: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  escrowBalance: TypedContractMethod<[], [bigint], "view">;

  faucetAmount: TypedContractMethod<[], [bigint], "view">;

  faucetCooldown: TypedContractMethod<[], [bigint], "view">;

  lastFaucetClaim: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  lastWithdrawalDay: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  maxWithdrawalPerTx: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  remainingDailyWithdrawal: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setBackendSigner: TypedContractMethod<
    [_signer: AddressLike],
    [void],
    "nonpayable"
  >;

  setFaucetSettings: TypedContractMethod<
    [_amount: BigNumberish, _cooldown: BigNumberish],
    [void],
    "nonpayable"
  >;

  setWithdrawalLimits: TypedContractMethod<
    [_maxPerTx: BigNumberish, _dailyLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  timeUntilNextClaim: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  token: TypedContractMethod<[], [string], "view">;

  totalDeposited: TypedContractMethod<[], [bigint], "view">;

  totalFaucetClaims: TypedContractMethod<[], [bigint], "view">;

  totalWithdrawn: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<
    [amount: BigNumberish, nonce: BigNumberish, signature: BytesLike],
    [void],
    "nonpayable"
  >;

  withdrawalNonces: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "backendSigner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "canClaim"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "claimToTrading"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "dailyWithdrawalLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dailyWithdrawn"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "escrowBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "faucetAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "faucetCooldown"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastFaucetClaim"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastWithdrawalDay"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxWithdrawalPerTx"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "remainingDailyWithdrawal"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBackendSigner"
  ): TypedContractMethod<[_signer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFaucetSettings"
  ): TypedContractMethod<
    [_amount: BigNumberish, _cooldown: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setWithdrawalLimits"
  ): TypedContractMethod<
    [_maxPerTx: BigNumberish, _dailyLimit: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "timeUntilNextClaim"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalDeposited"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalFaucetClaims"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalWithdrawn"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [amount: BigNumberish, nonce: BigNumberish, signature: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawalNonces"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "BackendSignerUpdated"
  ): TypedContractEvent<
    BackendSignerUpdatedEvent.InputTuple,
    BackendSignerUpdatedEvent.OutputTuple,
    BackendSignerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DepositedToTrading"
  ): TypedContractEvent<
    DepositedToTradingEvent.InputTuple,
    DepositedToTradingEvent.OutputTuple,
    DepositedToTradingEvent.OutputObject
  >;
  getEvent(
    key: "FaucetClaimedToTrading"
  ): TypedContractEvent<
    FaucetClaimedToTradingEvent.InputTuple,
    FaucetClaimedToTradingEvent.OutputTuple,
    FaucetClaimedToTradingEvent.OutputObject
  >;
  getEvent(
    key: "FaucetSettingsUpdated"
  ): TypedContractEvent<
    FaucetSettingsUpdatedEvent.InputTuple,
    FaucetSettingsUpdatedEvent.OutputTuple,
    FaucetSettingsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalLimitsUpdated"
  ): TypedContractEvent<
    WithdrawalLimitsUpdatedEvent.InputTuple,
    WithdrawalLimitsUpdatedEvent.OutputTuple,
    WithdrawalLimitsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawnFromTrading"
  ): TypedContractEvent<
    WithdrawnFromTradingEvent.InputTuple,
    WithdrawnFromTradingEvent.OutputTuple,
    WithdrawnFromTradingEvent.OutputObject
  >;

  filters: {
    "BackendSignerUpdated(address,address)": TypedContractEvent<
      BackendSignerUpdatedEvent.InputTuple,
      BackendSignerUpdatedEvent.OutputTuple,
      BackendSignerUpdatedEvent.OutputObject
    >;
    BackendSignerUpdated: TypedContractEvent<
      BackendSignerUpdatedEvent.InputTuple,
      BackendSignerUpdatedEvent.OutputTuple,
      BackendSignerUpdatedEvent.OutputObject
    >;

    "DepositedToTrading(address,uint256)": TypedContractEvent<
      DepositedToTradingEvent.InputTuple,
      DepositedToTradingEvent.OutputTuple,
      DepositedToTradingEvent.OutputObject
    >;
    DepositedToTrading: TypedContractEvent<
      DepositedToTradingEvent.InputTuple,
      DepositedToTradingEvent.OutputTuple,
      DepositedToTradingEvent.OutputObject
    >;

    "FaucetClaimedToTrading(address,uint256)": TypedContractEvent<
      FaucetClaimedToTradingEvent.InputTuple,
      FaucetClaimedToTradingEvent.OutputTuple,
      FaucetClaimedToTradingEvent.OutputObject
    >;
    FaucetClaimedToTrading: TypedContractEvent<
      FaucetClaimedToTradingEvent.InputTuple,
      FaucetClaimedToTradingEvent.OutputTuple,
      FaucetClaimedToTradingEvent.OutputObject
    >;

    "FaucetSettingsUpdated(uint256,uint256)": TypedContractEvent<
      FaucetSettingsUpdatedEvent.InputTuple,
      FaucetSettingsUpdatedEvent.OutputTuple,
      FaucetSettingsUpdatedEvent.OutputObject
    >;
    FaucetSettingsUpdated: TypedContractEvent<
      FaucetSettingsUpdatedEvent.InputTuple,
      FaucetSettingsUpdatedEvent.OutputTuple,
      FaucetSettingsUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "WithdrawalLimitsUpdated(uint256,uint256)": TypedContractEvent<
      WithdrawalLimitsUpdatedEvent.InputTuple,
      WithdrawalLimitsUpdatedEvent.OutputTuple,
      WithdrawalLimitsUpdatedEvent.OutputObject
    >;
    WithdrawalLimitsUpdated: TypedContractEvent<
      WithdrawalLimitsUpdatedEvent.InputTuple,
      WithdrawalLimitsUpdatedEvent.OutputTuple,
      WithdrawalLimitsUpdatedEvent.OutputObject
    >;

    "WithdrawnFromTrading(address,uint256)": TypedContractEvent<
      WithdrawnFromTradingEvent.InputTuple,
      WithdrawnFromTradingEvent.OutputTuple,
      WithdrawnFromTradingEvent.OutputObject
    >;
    WithdrawnFromTrading: TypedContractEvent<
      WithdrawnFromTradingEvent.InputTuple,
      WithdrawnFromTradingEvent.OutputTuple,
      WithdrawnFromTradingEvent.OutputObject
    >;
  };
}
