/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FakeDexEscrow } from "./FakeDexEscrow";
export type { IMintableToken } from "./IMintableToken";
