/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as fakeDexEscrowSol from "./FakeDexEscrow.sol";
export { TFAKEUSD__factory } from "./TFAKEUSD__factory";
